theme: jekyll-theme-minimal
title: Búsqueda del tesoro
description: Duodécimo cumpleaños de Adriana 

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - adriana.md
  - README.md
